#!/bin/bash
# =============================================================================
# DINO-MM RGB+IR+Video Pretraining Script
# Extends the image-only pipeline with video DataLoader for temporal training.
#
# Usage:
#   # Step 0: Generate video manifests (run once)
#   bash scripts/run_pretrain_video.sh manifest
#
#   # Step 1: Precheck (dry-run with video data)
#   bash scripts/run_pretrain_video.sh precheck
#
#   # Step 2: Full training with video
#   bash scripts/run_pretrain_video.sh train
#
#   # Default (no arg): runs training
#   bash scripts/run_pretrain_video.sh
# =============================================================================

set -euo pipefail

# --- Mode ---
MODE="${1:-train}"

# --- Configuration ---
PROJ_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJ_DIR"

# Image data: merged manifest
DATA_PATH="/root/autodl-tmp/train1/manifests/merged_full_pretrain_v2_clean.json"
DATA_MODE="file"

# Video data: combined manifest (generated by generate_video_manifests.py)
VIDEO_MANIFEST="/root/autodl-tmp/data/manifests/video_all.json"
VIDEO_BATCH_SIZE=8
VIDEO_NUM_WORKERS=4
VIDEO_PREFETCH_FACTOR=2
VIDEO_PERSISTENT_WORKERS=True
VIDEO_TARGET_SIZE=224
VIDEO_STEP_INTERVAL=0
NUM_FRAMES=4

# Model
ARCH="vit_small"
PATCH_SIZE=16
IN_CHANS=4
FUSION="concat"
OUT_DIM=65536
DROP_PATH_RATE=0.1
USE_GRADIENT_CHECKPOINTING=True
ACCUMULATE_GRAD_BATCHES=1

# Pretrained
PRETRAINED="/root/autodl-tmp/train1/dino_deitsmall16_pretrain.pth"
RESUME=""

# Training
EPOCHS=50
BATCH_SIZE=64
LR=0.0005
WARMUP_EPOCHS=5
MIN_LR=1e-6
WEIGHT_DECAY=0.04
WEIGHT_DECAY_END=0.4
CLIP_GRAD=3.0
MOMENTUM_TEACHER=0.996
FREEZE_LAST_LAYER=1

# Temperature
WARMUP_TEACHER_TEMP=0.04
TEACHER_TEMP=0.07
WARMUP_TEACHER_TEMP_EPOCHS=5

# Multi-crop
GLOBAL_CROP_SIZE=224
LOCAL_CROP_SIZE=98
LOCAL_CROPS_NUMBER=8

# Multi-granularity
NUM_CLUSTERS=8
PROJ_DIM=256

# Loss weights
W_DINO_VIDEO=0.2
W_MGCL=0.2
W_VIEW=0.1
W_BRIDGE=0.05
W_TCL=0.05
W_TCL_PATCH=0.1
ADAPTIVE_WEIGHTING=True
USE_PCGRAD=True
IMAGE_AUX_RAMP_EPOCHS=5
IMAGE_AUX_START_SCALE=0.5
VIDEO_AUX_RAMP_EPOCHS=8
VIDEO_AUX_START_SCALE=0.25

# Temporal
TEMPORAL_LAYERS=2
TCL_TEMPERATURE=0.07
TCL_PATCH_TEMPERATURE=0.1
TCL_SPATIAL_SIGMA_BASE=2.0
TCL_SPATIAL_SIGMA_SCALE=0.5

# View-domain bridge
BRIDGE_PROJ_DIM=256
BRIDGE_NUM_PROTOTYPES=64
BRIDGE_SINKHORN_ITERS=3
BRIDGE_SINKHORN_TEMP=0.1
BRIDGE_PROTOTYPE_EMA=0.999

# Output
RUN_TAG="$(date +%Y%m%d_%H%M%S)"
OUTPUT_DIR="/root/autodl-tmp/train1/pretrain_video_${RUN_TAG}"
SAVE_EVERY=5
LOG_EVERY=50

# Mixed precision
USE_FP16=True

# Workers
NUM_WORKERS=8
PREFETCH_FACTOR=2
PERSISTENT_WORKERS=True

# Wandb
WANDB_PROJECT="DINO-MM"
WANDB_RUN_NAME="video_${ARCH}_p${PATCH_SIZE}_${RUN_TAG}"

# --- Detect GPU count ---
if command -v nvidia-smi >/dev/null 2>&1; then
    NUM_GPUS=$(nvidia-smi -L 2>/dev/null | wc -l)
    if [ "$NUM_GPUS" -lt 1 ]; then
        NUM_GPUS=1
    fi
else
    NUM_GPUS=1
fi
echo "============================================="
echo "DINO-MM RGB+IR+Video Pretraining"
echo "============================================="
echo "Mode: $MODE"
echo "Detected ${NUM_GPUS} GPU(s)"
echo "Image data: $DATA_PATH"
echo "Video data: $VIDEO_MANIFEST"
echo "Arch: $ARCH, Patch: $PATCH_SIZE, Channels: $IN_CHANS, Fusion: $FUSION"
echo "Epochs: $EPOCHS, Image Batch/GPU: $BATCH_SIZE, Video Batch/GPU: $VIDEO_BATCH_SIZE"
echo "Video frames: $NUM_FRAMES, Target size: $VIDEO_TARGET_SIZE"
echo "Losses: dino_v=$W_DINO_VIDEO mgcl=$W_MGCL view=$W_VIEW bridge=$W_BRIDGE tcl=$W_TCL tcl_patch=$W_TCL_PATCH"
echo "Adaptive weighting: $ADAPTIVE_WEIGHTING, PCGrad: $USE_PCGRAD"
echo "Video step interval: ${VIDEO_STEP_INTERVAL} (0=auto)"
echo "Output: $OUTPUT_DIR"
echo "============================================="

# --- Handle manifest generation ---
if [ "$MODE" = "manifest" ]; then
    echo ""
    echo ">>> Generating video manifests <<<"
    echo ""
    python3 scripts/generate_video_manifests.py \
        --uav_human_root /root/autodl-tmp/data/UAV-Human/ActionRecognition \
        --aerial_rgbt_root /root/autodl-tmp/data/aerial-rgbt/labeled_thermal_singles \
        --output_dir /root/autodl-tmp/data/manifests
    echo "Done! Manifests saved to /root/autodl-tmp/data/manifests/"
    exit 0
fi

# --- Check files exist ---
if [ ! -f "$DATA_PATH" ]; then
    echo "ERROR: Image manifest not found: $DATA_PATH"
    exit 1
fi

if [ ! -f "$VIDEO_MANIFEST" ]; then
    echo "ERROR: Video manifest not found: $VIDEO_MANIFEST"
    echo "Run: bash scripts/run_pretrain_video.sh manifest"
    exit 1
fi

if [ -n "$PRETRAINED" ] && [ ! -f "$PRETRAINED" ]; then
    echo "WARNING: Pretrained weights not found: $PRETRAINED"
    echo "Training from scratch instead."
    PRETRAINED=""
fi

# --- Create output directory ---
mkdir -p "$OUTPUT_DIR"

# --- Common args ---
COMMON_ARGS="
    --arch $ARCH
    --patch_size $PATCH_SIZE
    --in_chans $IN_CHANS
    --fusion $FUSION
    --out_dim $OUT_DIM
    --drop_path_rate $DROP_PATH_RATE
    --use_gradient_checkpointing $USE_GRADIENT_CHECKPOINTING
    --accumulate_grad_batches $ACCUMULATE_GRAD_BATCHES
    --data_path $DATA_PATH
    --data_mode $DATA_MODE
    --output_dir $OUTPUT_DIR
    --epochs $EPOCHS
    --batch_size_per_gpu $BATCH_SIZE
    --lr $LR
    --warmup_epochs $WARMUP_EPOCHS
    --min_lr $MIN_LR
    --weight_decay $WEIGHT_DECAY
    --weight_decay_end $WEIGHT_DECAY_END
    --clip_grad $CLIP_GRAD
    --momentum_teacher $MOMENTUM_TEACHER
    --freeze_last_layer $FREEZE_LAST_LAYER
    --warmup_teacher_temp $WARMUP_TEACHER_TEMP
    --teacher_temp $TEACHER_TEMP
    --warmup_teacher_temp_epochs $WARMUP_TEACHER_TEMP_EPOCHS
    --global_crop_size $GLOBAL_CROP_SIZE
    --local_crop_size $LOCAL_CROP_SIZE
    --local_crops_number $LOCAL_CROPS_NUMBER
    --num_clusters $NUM_CLUSTERS
    --proj_dim $PROJ_DIM
    --w_dino_video $W_DINO_VIDEO
    --w_mgcl $W_MGCL
    --w_view $W_VIEW
    --w_bridge $W_BRIDGE
    --adaptive_weighting $ADAPTIVE_WEIGHTING
    --aux_loss_ramp_epochs $IMAGE_AUX_RAMP_EPOCHS
    --aux_loss_start_scale $IMAGE_AUX_START_SCALE
    --video_aux_ramp_epochs $VIDEO_AUX_RAMP_EPOCHS
    --video_aux_start_scale $VIDEO_AUX_START_SCALE
    --w_tcl $W_TCL
    --w_tcl_patch $W_TCL_PATCH
    --bridge_proj_dim $BRIDGE_PROJ_DIM
    --bridge_num_prototypes $BRIDGE_NUM_PROTOTYPES
    --bridge_sinkhorn_iters $BRIDGE_SINKHORN_ITERS
    --bridge_sinkhorn_temp $BRIDGE_SINKHORN_TEMP
    --bridge_prototype_ema $BRIDGE_PROTOTYPE_EMA
    --save_every $SAVE_EVERY
    --log_every $LOG_EVERY
    --use_fp16 $USE_FP16
    --num_workers $NUM_WORKERS
    --prefetch_factor $PREFETCH_FACTOR
    --persistent_workers $PERSISTENT_WORKERS
    --use_pcgrad $USE_PCGRAD
    --video_manifest $VIDEO_MANIFEST
    --video_batch_size $VIDEO_BATCH_SIZE
    --video_num_workers $VIDEO_NUM_WORKERS
    --video_prefetch_factor $VIDEO_PREFETCH_FACTOR
    --video_persistent_workers $VIDEO_PERSISTENT_WORKERS
    --video_target_size $VIDEO_TARGET_SIZE
    --video_step_interval $VIDEO_STEP_INTERVAL
    --num_frames $NUM_FRAMES
    --temporal_layers $TEMPORAL_LAYERS
    --tcl_temperature $TCL_TEMPERATURE
    --tcl_patch_temperature $TCL_PATCH_TEMPERATURE
    --tcl_spatial_sigma_base $TCL_SPATIAL_SIGMA_BASE
    --tcl_spatial_sigma_scale $TCL_SPATIAL_SIGMA_SCALE
    --wandb_project $WANDB_PROJECT
    --wandb_run_name $WANDB_RUN_NAME
"

# Optional args
if [ -n "$PRETRAINED" ]; then
    COMMON_ARGS="$COMMON_ARGS --pretrained $PRETRAINED"
fi
if [ -n "$RESUME" ]; then
    COMMON_ARGS="$COMMON_ARGS --resume $RESUME"
fi

# --- Mode-specific args ---
case "$MODE" in
    precheck)
        echo ""
        echo ">>> PRECHECK: 500 samples dry-run with video pipeline <<<"
        echo ""
        MODE_ARGS="--strict_loading True --dry_run_samples 500 --max_load_fail_ratio 0"
        ;;
    train)
        echo ""
        echo ">>> TRAINING: image + video, fault-tolerant mode <<<"
        echo ""
        MODE_ARGS="--strict_loading False --dry_run_samples 0 --max_load_fail_ratio 0.001"
        ;;
    *)
        echo "Unknown mode: $MODE. Use 'manifest', 'precheck', or 'train'."
        exit 1
        ;;
esac

# --- Run ---
if [ "$NUM_GPUS" -gt 1 ]; then
    echo "Multi-GPU with ${NUM_GPUS} GPUs"
    PYTHONUNBUFFERED=1 torchrun --nproc_per_node=$NUM_GPUS main_dino_rgbir.py \
        $COMMON_ARGS $MODE_ARGS \
        2>&1 | tee "$OUTPUT_DIR/${MODE}_log.txt"
else
    echo "Single-GPU"
    PYTHONUNBUFFERED=1 python main_dino_rgbir.py \
        $COMMON_ARGS $MODE_ARGS \
        2>&1 | tee "$OUTPUT_DIR/${MODE}_log.txt"
fi

echo ""
if [ "$MODE" = "precheck" ]; then
    echo "Precheck complete! Review output above."
    echo "If all OK, run: bash scripts/run_pretrain_video.sh train"
else
    echo "Training complete! Checkpoints saved to: $OUTPUT_DIR"
fi
